-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jul 20, 2022 at 04:42 PM
-- Server version: 10.2.44-MariaDB
-- PHP Version: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `southtou_witp`
--

-- --------------------------------------------------------

--
-- Table structure for table `pubcrawls`
--

CREATE TABLE `pubcrawls` (
  `id` int(11) NOT NULL,
  `city` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `start_time` datetime NOT NULL,
  `duration` int(11) NOT NULL,
  `meeting_point` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `stops` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `durations` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `geojson` longtext COLLATE utf8_unicode_ci NOT NULL,
  `status` enum('Ready','Started') COLLATE utf8_unicode_ci NOT NULL,
  `agent_id` int(11) DEFAULT NULL,
  `enable_timeline` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `actual_place` enum('1','2','3','4','5','6','7','8','9','10') COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `pubcrawls`
--

INSERT INTO `pubcrawls` (`id`, `city`, `start_time`, `duration`, `meeting_point`, `stops`, `durations`, `geojson`, `status`, `agent_id`, `enable_timeline`, `actual_place`) VALUES
(69, 'Malaga', '2022-06-09 00:00:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(70, 'Malaga', '2022-06-08 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(71, 'Malaga', '2022-06-09 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(72, 'Malaga', '2022-06-11 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_The Museum, Calle Convalecientes, Malaga_Sala BUBBLES, Calle Martires, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(73, 'Malaga', '2022-06-13 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', 2, 'false', '1'),
(74, 'Malaga', '2022-06-14 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\r\n      \"type\": \"FeatureCollection\",\r\n      \"features\": [\r\n    \r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.41709776603106,\r\n            36.72365219204769\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421585459408515,\r\n            36.7223829789638\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421705048630165,\r\n            36.72232749160218\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421288411859857,\r\n            36.72214151555827\r\n          ]\r\n        }\r\n      }\r\n      \r\n      ]\r\n    }', 'Ready', 2, 'false', '1'),
(75, 'Malaga', '2022-06-15 21:31:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\r\n      \"type\": \"FeatureCollection\",\r\n      \"features\": [\r\n    \r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.41709776603106,\r\n            36.72365219204769\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421585459408515,\r\n            36.7223829789638\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421705048630165,\r\n            36.72232749160218\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421288411859857,\r\n            36.72214151555827\r\n          ]\r\n        }\r\n      }\r\n      \r\n      ]\r\n    }', 'Ready', NULL, 'false', '1'),
(76, 'Malaga', '2022-06-16 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\r\n      \"type\": \"FeatureCollection\",\r\n      \"features\": [\r\n    \r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.41709776603106,\r\n            36.72365219204769\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421585459408515,\r\n            36.7223829789638\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421705048630165,\r\n            36.72232749160218\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421288411859857,\r\n            36.72214151555827\r\n          ]\r\n        }\r\n      }\r\n      \r\n      ]\r\n    }', 'Ready', NULL, 'false', '1'),
(77, 'Malaga', '2022-06-17 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\r\n      \"type\": \"FeatureCollection\",\r\n      \"features\": [\r\n    \r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.41709776603106,\r\n            36.72365219204769\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421585459408515,\r\n            36.7223829789638\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421705048630165,\r\n            36.72232749160218\r\n          ]\r\n        }\r\n      }\r\n      ,\r\n        {\r\n      \"type\": \"Feature\",\r\n      \"properties\": {\r\n        \"marker-color\": \"#7e7e7e\",\r\n        \"marker-size\": \"medium\",\r\n        \"marker-symbol\": \"\",\r\n      \r\n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\r\n      },\r\n        \"geometry\": {\r\n          \"type\": \"Point\",\r\n          \"coordinates\": [\r\n      \r\n            -4.421288411859857,\r\n            36.72214151555827\r\n          ]\r\n        }\r\n      }\r\n      \r\n      ]\r\n    }', 'Ready', 2, 'false', '1'),
(78, 'Malaga', '2022-06-18 22:30:00', 4, 'Smile Inc, Calle Nosquera, Malaga', 'Smile Inc, Calle Nosquera, Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '55,55,35,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(80, 'Malaga', '2022-06-21 17:30:00', 4, 'Smile Inc, Calle Nosquera, Malaga', 'Smile Inc, Calle Nosquera, Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '55,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(81, 'Malaga', '2022-06-23 15:30:00', 4, 'Merced 14. Plaza de la Merced 14', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Smile Inc, Calle Nosquera, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '45,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(82, 'Malaga', '2022-06-28 15:30:00', 4, 'Merced 14. Plaza de la Merced 14', 'Smile Inc, Calle Nosquera, Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,55,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(83, 'Malaga', '2022-06-28 16:00:00', 4, 'Merced 14. Plaza de la Merced 14', 'Smile Inc, Calle Nosquera, Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,55,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(84, 'Malaga', '2022-06-29 18:30:00', 4, 'Merced 14. Plaza de la Merced 14', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Smile Inc, Calle Nosquera, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,55,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(85, 'Malaga', '2022-06-30 15:00:00', 4, 'Merced 14. Plaza de la Merced 14', 'Smile Inc, Calle Nosquera, Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,45,55', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(86, 'Malaga', '2022-06-30 16:35:00', 4, 'Merced 14. Plaza de la Merced 14', 'Smile Inc, Calle Nosquera, Malaga_Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Seven O clock, Calle Comedias, Malaga_Sala Gold, Calle Luis de Velazquez, Malaga', '45,45,45,55', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala Gold, Calle Luis de Velazquez, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421288411859857,\n            36.72214151555827\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(87, 'Malaga', '2022-07-05 22:30:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'true', '1'),
(88, 'Malaga', '2022-07-07 20:00:00', 4, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,45,45', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(89, 'Malaga', '2022-07-20 17:18:00', 4, 'Merced 14. Plaza de la Merced 14', 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga_Camden Lock Malaga, Calle Convalecientes, Malaga_Gallery Club, Calle Convalecientes, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,45,55', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.41709776603106,\n            36.72365219204769\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Camden Lock Malaga, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421585459408515,\n            36.7223829789638\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Gallery Club, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421705048630165,\n            36.72232749160218\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1'),
(90, 'Malaga', '2022-07-20 17:28:00', 4, 'Smile Inc, Calle Nosquera, Malaga', 'Smile Inc, Calle Nosquera, Malaga_The Museum, Calle Convalecientes, Malaga_Seven O clock, Calle Comedias, Malaga_Sala BUBBLES, Calle Martires, Malaga', '45,45,45,55', '{\n      \"type\": \"FeatureCollection\",\n      \"features\": [\n    \n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Smile Inc, Calle Nosquera, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422135203429746,\n            36.722955203904306\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"The Museum, Calle Convalecientes, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421773785371996,\n            36.72226183562587\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Seven O clock, Calle Comedias, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.421640370730702,\n            36.722829361712165\n          ]\n        }\n      }\n      ,\n        {\n      \"type\": \"Feature\",\n      \"properties\": {\n        \"marker-color\": \"#7e7e7e\",\n        \"marker-size\": \"medium\",\n        \"marker-symbol\": \"\",\n      \n        \"name\": \"Sala BUBBLES, Calle Martires, Malaga\"\n      },\n        \"geometry\": {\n          \"type\": \"Point\",\n          \"coordinates\": [\n      \n            -4.422687147770784,\n            36.722162277629174\n          ]\n        }\n      }\n      \n      ]\n    }', 'Ready', NULL, 'false', '1');

-- --------------------------------------------------------

--
-- Table structure for table `suggestions`
--

CREATE TABLE `suggestions` (
  `id` int(11) NOT NULL,
  `stop` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `longitude` varchar(256) COLLATE utf8_unicode_ci NOT NULL,
  `latitude` varchar(256) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `suggestions`
--

INSERT INTO `suggestions` (`id`, `stop`, `longitude`, `latitude`) VALUES
(1, 'Merced 14. Plaza de la Merced 14', '-4.417598247528076', '36.72371616684815'),
(2, 'Picasso Bar Tapas, Pl. de la Merced, 20, 29012 Malaga', '-4.41709776603106', '36.72365219204769'),
(3, 'Camden Lock Malaga, Calle Convalecientes, Malaga', '-4.421585459408515', '36.7223829789638'),
(4, 'Gallery Club, Calle Convalecientes, Malaga', '-4.421705048630165', '36.72232749160218'),
(5, 'The Museum, Calle Convalecientes, Malaga', '-4.421773785371996', '36.72226183562587'),
(6, 'Smile Inc, Calle Nosquera, Malaga', '-4.422135203429746', '36.722955203904306'),
(7, 'Seven O clock, Calle Comedias, Malaga', '-4.421640370730702', '36.722829361712165'),
(8, 'Sala BUBBLES, Calle Martires, Malaga', '-4.422687147770784', '36.722162277629174'),
(9, 'Sala Gold, Calle Luis de Velazquez, Malaga', '-4.421288411859857', '36.72214151555827');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `role` enum('Agent','Admin') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'Agent',
  `longitude` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `latitude` varchar(256) COLLATE utf8_unicode_ci DEFAULT NULL,
  `verification_status` varchar(255) COLLATE utf8_unicode_ci NOT NULL DEFAULT '0',
  `verification_hash` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `last_position_update_time` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `email`, `name`, `password`, `role`, `longitude`, `latitude`, `verification_status`, `verification_hash`, `last_position_update_time`) VALUES
(2, 'henry.wigfull@googlemail.com', 'Henry Wigfull', '$2y$10$2oElijxAEKhpycjnjAzJzuZ2O1OboHM/4BwzT.0rKnH.kSXJwG5Ri', 'Agent', '-4.420221', '36.7223233', '1', NULL, NULL),
(21, 'it@southtours.es', 'South Tours', '$2y$10$hT9AkA.5VcmxAMsELUb8keB9AoCFcpGMjpn.8B9YgVt3B5eDvvew6', 'Admin', '-4.4201896', '36.722276', '1', '$2y$10$rU0/RnytAB9HHsqsJBWpeeBT4MsVnTH6pU3R0DU10FK5bsYhNj42.', NULL);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pubcrawls`
--
ALTER TABLE `pubcrawls`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `suggestions`
--
ALTER TABLE `suggestions`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `pubcrawls`
--
ALTER TABLE `pubcrawls`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=91;

--
-- AUTO_INCREMENT for table `suggestions`
--
ALTER TABLE `suggestions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=10;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=32;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
